export const cityNames = [
  { id: 1, name: "abu Dhabi" },
  { id: 2, name: "ahmedabad" },
  { id: 3, name: "amsterdam" },
  { id: 4, name: "bangkok" },
  { id: 5, name: "beijing" },
  { id: 6, name: "bengaluru" },
  { id: 7, name: "berlin" },
  { id: 8, name: "cairo" },
  { id: 9, name: "cape Town" },
  { id: 10, name: "chennai" },
  { id: 11, name: "chicago" },
  { id: 12, name: "colombo" },
  { id: 13, name: "delhi" },
  { id: 14, name: "dhaka" },
  { id: 15, name: "dubai" },
  { id: 16, name: "giza" },
  { id: 17, name: "hanoi" },
  { id: 18, name: "hong Kong" },
  { id: 19, name: "islamabad" },
  { id: 20, name: "istanbul" },
  { id: 21, name: "jaipur" },
  { id: 22, name: "jerusalem" },
  { id: 23, name: "kanpur" },
  { id: 24, name: "kathmandu" },
  { id: 25, name: "kolkata" },
  { id: 26, name: "kuwait" },
  { id: 27, name: "kyiv" },
  { id: 28, name: "kyoto" },
  { id: 29, name: "la Paz" },
  { id: 30, name: "lagos" },
  { id: 31, name: "lahore" },
  { id: 32, name: "libreville" },
  { id: 33, name: "lilongwe" },
  { id: 34, name: "lima" },
  { id: 35, name: "lisbon" },
  { id: 36, name: "ljubljana" },
  { id: 37, name: "lome" },
  { id: 38, name: "london" },
  { id: 39, name: "los Angeles" },
  { id: 40, name: "madrid" },
  { id: 41, name: "melbourne" },
  { id: 42, name: "mexico City" },
  { id: 43, name: "miami" },
  { id: 44, name: "montreal" },
  { id: 45, name: "moscow" },
  { id: 46, name: "mumbai" },
  { id: 47, name: "new York" },
  { id: 48, name: "osaka" },
  { id: 49, name: "ottawa" },
  { id: 50, name: "pune" },
  { id: 51, name: "rome" },
  { id: 52, name: "san Francisco" },
  { id: 53, name: "sao Paulo" },
  { id: 54, name: "seoul" },
  { id: 55, name: "shanghai" },
  { id: 56, name: "singapore" },
  { id: 57, name: "stockholm" },
  { id: 58, name: "surat" },
  { id: 59, name: "suva" },
  { id: 60, name: "sydney" },
  { id: 61, name: "tabriz" },
  { id: 62, name: "taipei" },
  { id: 63, name: "tokyo" },
  { id: 64, name: "toronto" },
  { id: 65, name: "torshavn" },
  { id: 66, name: "tripoli" },
  { id: 67, name: "tunis" },
  { id: 68, name: "ulan Bator" },
  { id: 69, name: "vaduz" },
  { id: 70, name: "valencia" },
  { id: 71, name: "valletta" },
  { id: 72, name: "vancouver" },
  { id: 73, name: "washington" },
  { id: 74, name: "yokohama" },
];
